export default {
  name: 'booking',
  title: 'Booking',
  type: 'document',
  fields: [
    {name: 'date', title: 'Date (legacy)', type: 'string'},
    {name: 'time', title: 'Time (legacy)', type: 'string'},

    {name: 'customerName', title: 'Customer Name', type: 'string'},
    {name: 'phone', title: 'Phone / Mobile', type: 'string'},
    {name: 'billingAddress', title: 'Billing / Correspondence Address', type: 'text'},
    {name: 'discord', title: 'Discord Username', type: 'string'},
    {name: 'email', title: 'Email', type: 'string'},
    {name: 'specs', title: 'PC Specs', type: 'text'},
    {name: 'mainGame', title: 'Main Game', type: 'string'},
    {name: 'message', title: 'Notes', type: 'text'},
    {
      name: 'orderId',
      title: 'Order ID',
      type: 'string',
      readOnly: true,
      description: 'Matches the booking document ID.',
    },
    {
      name: 'originalOrderId',
      title: 'Original Order ID (Upgrade)',
      type: 'string',
      readOnly: true,
      description: 'Links an upgrade payment back to the original booking.',
    },

    {
      name: 'status',
      title: 'Status',
      type: 'string',
      readOnly: true,
      description:
        'Change booking status through the backend/admin API so payment, refund, coupon, referral, and slot accounting stay consistent.',
      options: {
        list: ['pending', 'captured', 'completed', 'failed', 'refunded', 'cancelled'],
      },
      initialValue: 'pending',
    },

    {name: 'packageTitle', title: 'Package Title', type: 'string'},
    {name: 'packagePrice', title: 'Package Price', type: 'string'},

    {name: 'displayDate', title: 'Client Display Date', type: 'string'},
    {name: 'displayTime', title: 'Client Display Time', type: 'string'},
    {
      name: 'hostDate',
      title: 'Host Date',
      type: 'string',
      description: 'Date used for availability (matches host time zone).',
    },
    {
      name: 'hostTime',
      title: 'Host Time',
      type: 'string',
      description: 'Time label used to block slots, e.g. 2:00 PM.',
    },
    {name: 'hostTimeZone', title: 'Host Time Zone', type: 'string'},
    {name: 'localTimeZone', title: 'Client Time Zone', type: 'string'},
    {name: 'localTimeLabel', title: 'Client Local Time Label', type: 'string'},
    {name: 'startTimeUTC', title: 'Start Time (UTC)', type: 'datetime'},
    {name: 'slotLockId', title: 'Booking Slot Lock ID', type: 'string', readOnly: true},
    {name: 'slotReservationState', title: 'Slot Reservation State', type: 'string', readOnly: true},
    {name: 'requiresReschedule', title: 'Requires Reschedule', type: 'boolean'},
    {name: 'recoveryStatus', title: 'Recovery Status', type: 'string'},
    {name: 'recoveryReason', title: 'Recovery Reason', type: 'string'},
    {name: 'recoveryCreatedAt', title: 'Recovery Created At', type: 'datetime'},
    {name: 'recoveryNotificationStatus', title: 'Recovery Notification Status', type: 'string'},
    {name: 'recoveryNotificationLastAttemptAt', title: 'Recovery Notification Last Attempt', type: 'datetime'},
    {name: 'recoveryNotificationNextAttemptAt', title: 'Recovery Notification Next Attempt', type: 'datetime'},
    {name: 'recoveryNotificationAttemptCount', title: 'Recovery Notification Attempts', type: 'number'},
    {name: 'recoveryNotificationLastError', title: 'Recovery Notification Last Error', type: 'text'},
    {name: 'recoveryNotificationLeaseId', title: 'Recovery Notification Lease ID', type: 'string', readOnly: true},
    {name: 'recoveryNotificationLeaseExpiresAt', title: 'Recovery Notification Lease Expires', type: 'datetime', readOnly: true},
    {name: 'recoveryClientNotifiedAt', title: 'Recovery Client Notified At', type: 'datetime', readOnly: true},
    {name: 'recoveryOwnerNotifiedAt', title: 'Recovery Owner Notified At', type: 'datetime', readOnly: true},
    {name: 'originalRequestedStartTimeUTC', title: 'Original Requested Start', type: 'datetime'},

    {name: 'referralCode', title: 'Referral Code', type: 'string'},
    {
      name: 'referral',
      title: 'Referral Creator',
      type: 'reference',
      to: [{type: 'referral'}],
    },
    {name: 'discountPercent', title: 'Discount %', type: 'number'},
    {name: 'currency', title: 'Payment Currency', type: 'string'},
    {name: 'discountAmount', title: 'Discount Amount', type: 'number'},
    {name: 'grossAmount', title: 'Gross Amount', type: 'number'},
    {name: 'netAmount', title: 'Net Amount', type: 'number'},
    {name: 'commissionPercent', title: 'Commission %', type: 'number'},
    {name: 'commissionAmount', title: 'Commission Amount', type: 'number'},
    {name: 'referralAccountingApplied', title: 'Referral Count Applied', type: 'boolean', readOnly: true},
    {name: 'referralReversedAfterRefund', title: 'Referral Reversed After Refund', type: 'boolean', readOnly: true},

    {name: 'paymentProvider', title: 'Payment Provider', type: 'string'},
    {name: 'couponCode', title: 'Coupon Code', type: 'string'},
    {name: 'couponDiscountPercent', title: 'Coupon Discount %', type: 'number'},
    {name: 'couponDiscountAmount', title: 'Coupon Discount Amount', type: 'number'},
    {name: 'couponDiscountType', title: 'Coupon Discount Type', type: 'string'},
    {name: 'couponDiscountValue', title: 'Coupon Discount Value', type: 'number'},
    {name: 'couponRedemptionId', title: 'Coupon Redemption ID', type: 'string', readOnly: true},
    {name: 'couponRestoredAfterRefund', title: 'Coupon Restored After Refund', type: 'boolean', readOnly: true},

    {name: 'paypalOrderId', title: 'PayPal Order ID', type: 'string'},
    {name: 'payerEmail', title: 'Payer Email', type: 'string'},

    {name: 'razorpayOrderId', title: 'Razorpay Order ID', type: 'string'},
    {name: 'razorpayPaymentId', title: 'Razorpay Payment ID', type: 'string'},
    {name: 'paymentRecordId', title: 'Payment Record ID', type: 'string', readOnly: true},
    {name: 'paymentProofClaimId', title: 'Payment Proof Claim ID', type: 'string', readOnly: true},
    {name: 'paymentFinalizationLeaseId', title: 'Payment Finalization Lease ID', type: 'string', readOnly: true},
    {name: 'refundStatus', title: 'Refund Status', type: 'string'},
    {name: 'lastRefundId', title: 'Last Refund ID', type: 'string'},
    {name: 'lastRefundAt', title: 'Last Refund At', type: 'datetime'},
    {name: 'refundedAmount', title: 'Refunded Amount', type: 'number'},
    {name: 'processedRefundIds', title: 'Processed Refund IDs', type: 'array', of: [{type: 'string'}], readOnly: true},
    {name: 'refundAccountingAppliedAt', title: 'Refund Accounting Applied At', type: 'datetime', readOnly: true},
    {name: 'slotReleasedAfterRefund', title: 'Slot Released After Refund', type: 'boolean', readOnly: true},
    {name: 'emailDispatchDeferred', title: 'Email Dispatch Deferred', type: 'boolean'},
    {name: 'emailDispatchStatus', title: 'Email Dispatch Status', type: 'string'},
    {name: 'emailDispatchQueuedAt', title: 'Email Queued At', type: 'datetime'},
    {name: 'emailDispatchLastAttemptAt', title: 'Email Last Attempt At', type: 'datetime'},
    {name: 'emailDispatchNextAttemptAt', title: 'Email Next Attempt At', type: 'datetime'},
    {name: 'emailDispatchAttemptCount', title: 'Email Attempt Count', type: 'number'},
    {name: 'emailDispatchLastError', title: 'Email Last Error', type: 'text'},
    {name: 'emailDispatchLeaseId', title: 'Email Dispatch Lease ID', type: 'string', readOnly: true},
    {name: 'emailDispatchLeaseExpiresAt', title: 'Email Dispatch Lease Expires At', type: 'datetime', readOnly: true},
    {name: 'emailDispatchClientSentAt', title: 'Client Email Sent At', type: 'datetime'},
    {name: 'emailDispatchOwnerSentAt', title: 'Owner Email Sent At', type: 'datetime'},
    {name: 'createdAt', title: 'Created At', type: 'datetime', readOnly: true},
    {name: 'updatedAt', title: 'Updated At', type: 'datetime', readOnly: true},
  ],
}
