const eventField = {
  name: 'events',
  title: 'Events',
  type: 'array',
  of: [
    {
      type: 'object',
      fields: [
        {name: 'at', type: 'datetime'},
        {name: 'status', type: 'string'},
        {name: 'source', type: 'string'},
        {name: 'reason', type: 'string'},
        {name: 'dataJson', type: 'text'},
      ],
    },
  ],
}

export default {
  name: 'paymentRecord',
  title: 'Payment Record',
  type: 'document',
  fields: [
    {name: 'provider', type: 'string'},
    {name: 'status', type: 'string'},
    {name: 'sessionScope', type: 'string'},
    {name: 'startClaimId', type: 'string'},
    {name: 'quoteFingerprint', type: 'string'},
    {name: 'pricingFingerprint', type: 'text'},
    {name: 'providerIdempotencyKey', type: 'string'},
    {name: 'orderState', type: 'string'},
    {name: 'sessionExpiresAt', type: 'datetime'},
    {name: 'providerOrderId', type: 'string'},
    {name: 'providerPaymentId', type: 'string'},
    {name: 'paymentProofClaimId', type: 'string'},
    {name: 'couponReservationId', type: 'string'},
    {name: 'bookingId', type: 'string'},
    {name: 'bookingPayload', type: 'object', fields: [{name: 'dataJson', type: 'text'}]},
    {name: 'pricingSnapshot', type: 'object', fields: [{name: 'netAmount', type: 'number'}]},
    {
      name: 'holdSnapshot',
      type: 'object',
      fields: [
        {name: 'slotHoldId', type: 'string'},
        {name: 'slotHoldExpiresAt', type: 'datetime'},
        {name: 'phase', type: 'string'},
      ],
    },
    {name: 'providerPublicData', type: 'object', fields: [{name: 'currency', type: 'string'}]},
    {name: 'finalizationLeaseId', type: 'string'},
    {name: 'finalizationLeaseExpiresAt', type: 'datetime'},
    {name: 'recoveryReason', type: 'string'},
    {name: 'recoveryCategory', type: 'string'},
    {name: 'recoveryHttpStatus', type: 'number'},
    {name: 'recoveryAttemptCount', type: 'number'},
    {name: 'nextRecoveryAt', type: 'datetime'},
    {name: 'requiresReschedule', type: 'boolean'},
    {name: 'recoveryCaseId', type: 'string'},
    {name: 'recoveryNotificationRequired', type: 'boolean'},
    {name: 'refundState', type: 'string'},
    {name: 'refundRequiresBookingSync', type: 'boolean'},
    {name: 'refundProcessedAmountInSubunits', type: 'number'},
    {name: 'refundCurrency', type: 'string'},
    {
      name: 'refunds',
      type: 'array',
      of: [
        {
          type: 'object',
          fields: [
            {name: 'providerRefundId', type: 'string'},
            {name: 'providerPaymentId', type: 'string'},
            {name: 'eventType', type: 'string'},
            {name: 'status', type: 'string'},
            {name: 'amount', type: 'number'},
            {name: 'amountInSubunits', type: 'number'},
            {name: 'currency', type: 'string'},
            {name: 'reversed', type: 'boolean'},
            {name: 'updatedAt', type: 'datetime'},
          ],
        },
      ],
    },
    {name: 'attemptCount', type: 'number'},
    {name: 'lastAttemptAt', type: 'datetime'},
    {name: 'createdAt', type: 'datetime'},
    {name: 'updatedAt', type: 'datetime'},
    eventField,
  ],
}
